[workspace]
resolver = "2"
members = [
  'day_01', "utils",
]

[workspace.dependencies]
err-into = "1.0.1"
itertools = "0.13.0"
tracing = { version = "0.1.41" }
tracing-subscriber = { version = "0.3", features = ["local-time", "fmt", "env-filter", "time"] }
time = { version = "0.3.36", features = ["macros"] }