[package]
name = "day_06"
version = "0.1.0"
edition = "2021"

[dependencies]
utils = { path = "../utils" }
itertools = { workspace = true }
tracing = { workspace = true }
tramp = "0.3.0"
im = "15.1.0"
