[package]
name = "day_17"
version = "0.1.0"
edition = "2021"

[dependencies]
utils = { path = "../utils" }
itertools = { workspace = true }
tracing = { workspace = true }
tramp = { workspace = true }
derive_more = { version = "1.0.0", features = ["from"]}
