[package]
name = "day_10"
version = "0.1.0"
edition = "2021"

[dependencies]
utils = { path = "../utils" }
itertools = { workspace = true }
tracing = { workspace = true }
tramp = { workspace = true}
im = "15.1.0"
