[package]
name = "utils"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1.0.41"
err-into = { workspace = true}
tracing = { workspace = true}
time = { workspace = true}
tracing-subscriber = { workspace = true}
console = "0.15.8"
