[package]
name = "day_16"
version = "0.1.0"
edition = "2021"

[dependencies]
utils = { path = "../utils" }
itertools = { workspace = true }
tracing = { workspace = true }
im = { workspace = true }
tramp = { workspace = true }
